version: '3.7'

services:

  base:
    image: phaustin/base:may27
    build:
      context: base_image
    container_name: base_may27
    labels:
      - "traefik.enable=false"

  e211book:
    image: phaustin/e211book:may27
    build:
      context: e211book_image
    container_name: e211book_may27
    depends_on: [base]
    labels:
      - "traefik.enable=false"

  e211hub:
    build: e211hub_image
    image: phaustin/e211hub:may27
    container_name: e211hub_may27
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JHUB_OAUTH_CALLBACK_URL
      - JHUB_OAUTH_CLIENT_ID
      - JHUB_OAUTH_CLIENT_SECRET
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jhub.rule=Host(`jupyter.eoastest2.xyz`)"
      - traefik.http.routers.jhub.tls=true
      - traefik.http.routers.jhub.tls.certresolver=lets-encrypt
      - "traefik.http.routers.jhub.service=e211hub"
      - "traefik.http.services.e211hub.loadbalancer.server.port=8000"
    restart: on-failure
    networks:
      - traefik_net


networks:
  traefik_net:
    external: true
